/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.swingapplication.foofast.views.loginPage;



import javax.swing.*;

/**
 *
 * @author eramisme
 */
public class SignInFf extends JFrame {

//    private SignInController signInController;
    /**
     * Creates new form SignInFf
     */
    public SignInFf() {
        initComponents();
//        this.signInController = new SignInController();
        this.hide.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        show1 = new JLabel();
        jPanel3 = new JPanel();
        jPanel4 = new JPanel();
        jLabel4 = new JLabel();
        jLabel1 = new JLabel();
        jButton1 = new JButton();
        jLabel239 = new JLabel();
        jLabel240 = new JLabel();
        Username = new JTextField();
        Password = new JPasswordField();
        jCheckBox1 = new JCheckBox();
        jLabel5 = new JLabel();
        disable1 = new JLabel();
        hide = new JLabel();
        show = new JLabel();
        Signin = new rojerusan.RSMaterialButtonRectangle();

        show1.setIcon(new ImageIcon(getClass().getResource("/images/icons8_eye_20px_1.png"))); // NOI18N

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4.setText("Sign In");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(121, 106, 257, 62);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Don't have an account?");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(130, 450, 150, 20);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign Up");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(280, 450, 60, 19);

        jLabel239.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel239.setForeground(new java.awt.Color(255, 255, 255));
        jLabel239.setText("Username");
        jPanel4.add(jLabel239);
        jLabel239.setBounds(106, 213, 57, 16);

        jLabel240.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel240.setForeground(new java.awt.Color(255, 255, 255));
        jLabel240.setText("Password");
        jPanel4.add(jLabel240);
        jLabel240.setBounds(106, 296, 60, 16);

        Username.setBackground(new java.awt.Color(0, 102, 204));
        Username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setBorder(BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.add(Username);
        Username.setBounds(106, 235, 272, 31);

        Password.setBackground(new java.awt.Color(0, 102, 204));
        Password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.add(Password);
        Password.setBounds(106, 318, 272, 31);

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Remember Password");
        jPanel4.add(jCheckBox1);
        jCheckBox1.setBounds(106, 365, 140, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Forget Password?");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(285, 367, 101, 16);

        disable1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        disable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(disable1);
        disable1.setBounds(390, 320, 0, 30);

        hide.setIcon(new ImageIcon(getClass().getResource("/images/icons8_invisible_20px_1.png"))); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hideMousePressed(evt);
            }
        });
        jPanel4.add(hide);
        hide.setBounds(390, 320, 20, 30);

        show.setIcon(new ImageIcon(getClass().getResource("/images/icons8_eye_20px_1.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showMousePressed(evt);
            }
        });
        jPanel4.add(show);
        show.setBounds(390, 320, 20, 30);

        Signin.setBackground(new java.awt.Color(255, 255, 255));
        Signin.setForeground(new java.awt.Color(0, 102, 204));
        Signin.setText("Sign In");
        Signin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigninActionPerformed(evt);
            }
        });
        jPanel4.add(Signin);
        Signin.setBounds(130, 390, 220, 50);

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, 584, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SignUp SignUpFrame = new SignUp();
        SignUpFrame.setVisible(true);
        SignUpFrame.pack();
        SignUpFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMousePressed
        // TODO add your handling code here:
        show.setVisible(false);
        hide.setVisible(true);
        Password.setEchoChar((char)0);
        
    }//GEN-LAST:event_showMousePressed

    private void hideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMousePressed
        // TODO add your handling code here:
        show.setVisible(true);
        hide.setVisible(false);
        Password.setEchoChar('*');
        
    }//GEN-LAST:event_hideMousePressed

    private void SigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigninActionPerformed
        // TODO add your handling code here:

        String username = Username.getText();
        String password = Password.getText();

//        LoginRequest loginRequest = new LoginRequest(username, password);
//        UserResponse userResponse = signInController.signIn(loginRequest);
//        if(userResponse != null){
//            System.out.println("Dang nhap thanh cong");
//        }else{
//            System.out.println("Dang nhap that bai");
//        }
        
    }//GEN-LAST:event_SigninActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInFf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInFf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInFf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInFf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInFf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPasswordField Password;
    private rojerusan.RSMaterialButtonRectangle Signin;
    private JTextField Username;
    private JLabel disable1;
    private JLabel hide;
    private JButton jButton1;
    private JCheckBox jCheckBox1;
    private JLabel jLabel1;
    private JLabel jLabel239;
    private JLabel jLabel240;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JLabel show;
    private JLabel show1;
    // End of variables declaration//GEN-END:variables
}
