package com.swingapplication.foofast.views.chart;

import java.awt.*;

/**
 *
 * @author Pham Tan Nguyen
 */
public class RevenueForm extends javax.swing.JPanel {

    /**
     * Creates new form RevenueForm
     */
    public RevenueForm() {
        initComponents();
        chart.addLegend("Tổng doanh thu", new Color(0, 0, 255));
        chart.addLegend("Chi phí", new Color(180, 240, 255));
        chart.addLegend("Lợi nhuận", new Color(230,230,230));
//        chart.addLegend("Cost", new Color(139, 229, 222));
        chart.addData(new ModelChart("Tháng 1", new double[]{89_252_000, 34_785_000, 55_350_000}));
        chart.addData(new ModelChart("Tháng 2", new double[]{140_576_000, 41_576_000, 100_350_000}));
        chart.addData(new ModelChart("Tháng 3", new double[]{101_243_000, 38_252_000, 78_350_000}));
        chart.addData(new ModelChart("Tháng 4", new double[]{134_785_000, 47_785_000, 92_350_000}));
        chart.addData(new ModelChart("Tháng 5", new double[]{123_782_000, 40_252_000, 80_785_000}));
        chart.addData(new ModelChart("Tháng 6", new double[]{101_243_000, 47_785_000, 59_243_000}));
        chart.addData(new ModelChart("Tháng 7", new double[]{89_252_000, 36_350_000, 58_252_000}));
        chart.addData(new ModelChart("Tháng 8", new double[]{140_576_000,38_252_000, 112_576_000}));
        chart.addData(new ModelChart("Tháng 9", new double[]{167_785_000, 41_576_000, 126_782_000}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        chart = new Chart();
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

    }


    private Chart chart;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
