package com.swingapplication.foofast.views.chart;

import java.awt.*;

/**
 *
 * @author Pham Tan Nguyen
 */
public class TransactionForm extends javax.swing.JPanel {

    /**
     * Creates new form RevenueForm
     */
    public TransactionForm() {
        initComponents();
//        chart.addLegend("Tổng giao dịch tích lũy", new Color(0, 0, 255));
        chart.addLegend("Giao dịch trong tháng", new Color(0, 0, 255));
        chart.addLegend("Giao dịch triển vọng trên 1 triệu", new Color(180, 240, 255));

//        chart.addLegend("Cost", new Color(139, 229, 222));

        chart.addData(new ModelChart("Tháng 1", new double[]{1_667, 367}));
        chart.addData(new ModelChart("Tháng 2", new double[]{976, 239}));
        chart.addData(new ModelChart("Tháng 3", new double[]{998, 486}));
        chart.addData(new ModelChart("Tháng 4", new double[]{893, 203}));
        chart.addData(new ModelChart("Tháng 5", new double[]{802, 239}));
        chart.addData(new ModelChart("Tháng 6", new double[]{998, 307}));
        chart.addData(new ModelChart("Tháng 7", new double[]{957, 219}));
        chart.addData(new ModelChart("Tháng 8", new double[]{1_667, 486}));
        chart.addData(new ModelChart("Tháng 9", new double[]{976, 367}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        chart = new Chart();
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

    }


    private Chart chart;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
